version: 3

env:
  TF_CPP_MIN_LOG_LEVEL: 3

tasks:
  ae:train:
    cmds:
      - rye run python src/cli.py autoencoder train -c configs/train.toml
  ae:reconstruct:
    cmds:
      - rye run python src/cli.py autoencoder reconstruct -c configs/reconstruct.toml
  vae:train:
    cmds:
      - rye run python src/cli.py vae train -c configs/train.toml
  vae:reconstruct:
    cmds:
      - rye run python src/cli.py vae reconstruct -c configs/reconstruct.toml
