version: 3

tasks:
  init:
    cmds:
      - go install github.com/go-task/task/v3/cmd/task@latest
      - curl -sSf https://rye-up.com/get | bash
      - rye sync
  build:mechanisms:
    dir: src/mechanisms
    cmds:
      - rm -rf ../x86_64
      - rye run nrnivmodl
      - mv x86_64 ../x86_64
  run:
    deps:
      - run:positive
      - run:negative
      - run:propagation
  run:gap:
    dir: src
    cmds:
      - rye run python cli.py simulate-gap-junction -o ../outputs {{ .CLI_ARGS }}
  run:propagation:
    dir: src
    cmds:
      - rye run python cli.py simulate-epsp-propagation -o ../outputs
  run:net:
    dir: src
    cmds:
      - rye run python cli.py simulate-dentate-gyrus -o ../outputs {{ .CLI_ARGS }}
  analyze:cells:
    dir: src
    cmds:
      - rye run python cli.py analyze-intrinsic-properties -o ../outputs
  analyze:dentate-gyrus:
    dir: src
    cmds:
      - rye run python cli.py analyze-dentate-gyrus -o ../outputs {{ .CLI_ARGS }}
  analyze:dentate-gyrus:all:
    dir: src
    vars:
      IDS:
        sh: echo "SELECT id FROM jobs;" | sqlite3 ../outputs/dentate_gyrus.sqlite
    cmds:
      - for: { var: IDS, as: ID }
        task: analyze:dentate-gyrus
        vars:
          CLI_ARGS: --job-id {{ .ID }}
